import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class ChangeMe {
	
	private static final Logger logger = LoggerFactory.getLogger(ChangeMe.class);
	
    public static boolean someLibraryMethod() {
        return true;
    }
    
    public static void main(String[] args) {
    		logger.info("This project works : " + someLibraryMethod());
	}
}
