/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class ChangeMeTest {
    @Test public void testSomeLibraryMethod() {
        ChangeMe classUnderTest = new ChangeMe();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
